ci: wip

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -5,19 +5,46 @@
 #                   run.
 
 set -e
+if ! [ -z $CI ]; then
+  set -o xtrace
+fi
 
 cd "$(dirname "$0")/.."
 
+# Setup package
+stack_setup() {
+  echo "Stack package setup"
+  stack update
+  stack setup
+}
+
 # If stack is not installed then download and install
-if ! command -v stack &> /dev/null; then
+if ! [ -x "$(command -v stack)" ]; then
   echo "Command 'stack' not found. Installing..."
   curl -sSL https://get.haskellstack.org/ | sh
+  stack_setup
+elif [ -z $CI ]; then
+  stack_setup
 fi
 
-stack update
-stack setup
+# If yq is not installed then download and install
+if ! [ -x "$(command -v yq)" ]; then
+  echo "Command 'yq' not found. Installing..."
+  if [ -x "$(command -v snap)" ]; then
+    sudo snap install yq
+  elif [ -x "$(command -v brew)" ]; then
+    sudo brew install yq
+  else
+    echo "Could not install yq"
+    exit 1
+  fi
+fi
+# Install extra deps
+echo "Stack install extra deps"
+yq read stack.yaml 'extra-deps[*]' | xargs stack install
 
-# Setup precommit hook if not in CI
-if [[ -z $CI ]]; then
-    ./script/precommit
+# If not in CI
+if [ -z $CI ]; then
+  # Setup precommit hook
+  ./script/precommit
 fi
